### ISSUE TITLE
"Server Not Found" Listed as Valid

### ISSUE THREAD

**Issue by gjs---** [balvin-perrie/broken-link-checker#3]
The broken link:
`	<a href="http://www.devenshhw.org/">www.DevensHHW.org</a>`

Which should be:
`	<a href="http://www.devenshhw.com/">www.DevensHHW.com</a>`

Is listed in the "Valid Links" list, but with return status:
`	0   -  No Access-Control-Allow-Origin `

Even though Firefox says "We’re having trouble finding that site".  It should appear in the "Broken Links" list instead.

(This particular case intentionally uses the resource path as the link text, so that it is visible in printed copies.)

**Comment by balvin-perrie** [comment]
Thanks for the report. Will be fixed by the next release.
