### ISSUE TITLE
Mangled Link Is Not Flagged

### ISSUE THREAD

**Issue by gjs---** [balvin-perrie/broken-link-checker#4]
The following link appears not to be tested, even when the "Deep Search" option is selected:
`	<a href="../../AppData/Local/Temp/www.boltonlocal.org/initiatives/repair-cafe">www.boltonlocal.org/initiatives/repair-cafe</a>`

Apparently my HTML editor expanded it as a file URL from the HTTP URL which I entered incorrectly (missing protocol):
`	<a href="www.boltonlocal.org/initiatives/repair-cafe">www.boltonlocal.org/initiatives/repair-cafe</a>`

The link does not appear in either the "Broken Links" list or the "Valid Links" list.

Opening the link in Firefox produces a "File not found" error (404).

(This particular case intentionally uses the resource path as the link text, so that it is visible in printed copies.)

P.S.: This error is flagged on a page which was loaded from a web server, but not on a local page which was loaded through a "file:" URL.

**Comment by balvin-perrie** [comment]
Thanks for the report. Will be fixed by the next release.
