### ISSUE TITLE
Ignore a particular element?

### ISSUE THREAD

**Issue by AndrewJMitchell** [balvin-perrie/broken-link-checker#5]
Just started to use your tool on a site that contains a number of reports (in PDF format), the site is behind a login mechanism and I've found that every time I run the checker I get logged out of the site.  Is there a way to ignore specified elements on a page?

**Comment by balvin-perrie** [comment]
There is a new box to insert keywords that should get ignored. Also there is a checkbox that prevents automatic search to allow the user to update the keywords.

**Comment by AndrewJMitchell** [comment]
That works a treat!  Thank you ever so much for adding that option :)
